#!/bin/bash
set -e
source dev-container-features-test-lib

# This autogenerated/default test runs under installShellShims=false (set in
# scenarios.json). The Dev Container test harness bootstraps every container
# through /bin/sh, so it cannot start a container whose /bin/sh is replaced by
# the agentsh shim. Shim mediation -- the secure production default -- is
# validated separately by the Docker-based integration test under
# test/agentsh/integration/.

check "agentsh installed" bash -c "command -v agentsh"
check "agentsh version reports" bash -c "agentsh --version"
check "default policy installed" bash -c "test -f /etc/agentsh/policy.yaml"
check "authoritative server config installed" bash -c "test -f /etc/agentsh/config.yaml"
check "REST API private by default" bash -c "grep -q 'addr: \"127.0.0.1:18080\"' /etc/agentsh/config.yaml"
check "REST API unauthenticated by default" bash -c "grep -q 'type: \"none\"' /etc/agentsh/config.yaml"
check "runtime policy generated" bash -c "test -f /run/agentsh/policy.yaml"
check "server config loads runtime policy dir" bash -c "grep -q 'dir: \"/run/agentsh\"' /etc/agentsh/config.yaml"
check "shell shim binary installed" bash -c "test -x /usr/local/bin/agentsh-shell-shim"
check "shell shims not active when disabled" bash -c "test ! -e /bin/sh.real && test ! -e /bin/bash.real"

reportResults
